# Do NOT update manually; changes here will be overwritten by Copier
_commit: v1.21.1
_src_path: https://github.com/OCA/oca-addons-repo-template.git
ci: GitHub
convert_readme_fragments_to_markdown: false
generate_requirements_txt: true
github_check_license: true
github_ci_extra_env: {}
github_enable_codecov: true
github_enable_makepot: true
github_enable_stale_action: true
github_enforce_dev_status_compatibility: true
include_wkhtmltopdf: true
odoo_test_flavor: OCB
odoo_version: 16.0
org_name: KMEE
org_slug: KMEE
rebel_module_groups: []
repo_description: Welcome to our repository, dedicated to incubating OCA modules developed
    by KMEE. Our goal is to foster innovation and enhance the functionality of Odoo
    with cutting-edge solutions tailored to meet the diverse needs of businesses.
    By leveraging our expertise and commitment to quality, we aim to contribute robust
    and efficient modules that seamlessly integrate into the OCA ecosystem, driving
    productivity and growth for users worldwide.
repo_name: KMEE Odoo Addons
repo_slug: kmee-odoo-addons
repo_website: https://github.com/KMEE/kmee-odoo-addons
use_pyproject_toml: false
use_ruff: false

