# Copyright (C) 2025 KMEE Informatica LTDA - Luis Felipe Miléo
# License AGPL-3.0 or later (http://www.gnu.org/licenses/agpl).

from odoo import fields, models


class AccountMoveLine(models.Model):
    _inherit = "account.move.line"

    is_double_entry_line = fields.Boolean(
        string="Template Double Entry",
        default=False,
        copy=False,
        help="Indicates this line was auto-generated by a fiscal accounting template.",
    )
