from unittest.mock import patch

from odoo.tests.common import TransactionCase, tagged

from .fixtures import (
    GENERATE_BOLETO_PAYLOAD_DECRYPTED,
    SEND_CAPTURE_REQUEST_PAYLOAD,
    SEND_CAPTURE_REQUEST_RESPONSE,
    SEND_CAPTURE_REQUEST_RESPONSE_REGISTRADO,
)


@tagged("at_install", "post_install")
class TestPaymentTransaction(TransactionCase):
    def setUp(self):
        super().setUp()

        self.payment_provider = self.env.ref(
            "l10n_br_payment_boleto_pinbank.payment_acquirer_boleto_pinbank"
        )

        self.payment_provider.pinbank_user = "abcd1234"
        self.payment_provider.pinbank_secret = "secret"
        self.payment_provider.pinbank_channel = 10
        self.payment_provider.pinbank_client = 1000
        self.payment_provider.pinbank_request_origin = "1"
        self.payment_provider.state = "enabled"

        # Create a demo partner
        self.partner = self.env["res.partner"].create(
            {
                "email": "atendimento@testeboleto.com.br",
                "name": "Empresa Teste Boleto LTDA",
                "legal_name": "Empresa Teste Boleto LTDA",
                "street": "Rua Luiz Rubino",
                "district": "Jardim Wilma Flor",
                "city": "São Paulo",
                "zip": "08473-002",
                "state_id": self.env["res.country.state"]
                .search([("code", "=", "SP")], limit=1)
                .id,
                "country_id": self.env.ref("base.br").id,
                "cnpj_cpf": "73.145.637/0001-40",
            }
        )

        # Create a demo payment transaction
        self.payment_transaction = self.env["payment.transaction"].create(
            {
                "reference": "TEST123",
                "amount": 258.75,
                "due_date": "2025-04-22",
                "state": "draft",
                "currency_id": self.env.ref("base.BRL").id,
                "partner_id": self.partner.id,
                "provider_id": self.payment_provider.id,
                "provider_code": "boleto_pinbank",
                "boleto_penalty": 0.01,
                "boleto_interest": 0.01,
                "boleto_instructions": "Não receber após o vencimento",
            }
        )

    def test_boleto_pinbank_prepare_order_request_payload(self):
        """
        Test the `_boleto_pinbank_prepare_order_request_payload` method of the
        `payment_transaction` object.
        This test verifies that the payload generated by the method matches
        the expected decrypted payload (`GENERATE_BOLETO_PAYLOAD_DECRYPTED`).
        Assertions:
            - The generated payload is equal to the expected payload.
        """
        payload = (
            self.payment_transaction._boleto_pinbank_prepare_order_request_payload()
        )

        self.assertEqual(payload, GENERATE_BOLETO_PAYLOAD_DECRYPTED)

    def test_prepare_transaction_boleto_info(self):
        """
        Test the `_prepare_transaction_boleto_info` method of the payment transaction.

        This test verifies that the method correctly prepares the boleto information
        based on the provided response data. It checks the following:

        - The "our_number" field is correctly set.
        - The "digitable_line" field matches the expected format.
        - The "barcode" field is correctly generated.

        Note: The state transition is handled by `_process_notification_data`, not by
        `_prepare_transaction_boleto_info`, which only extracts boleto display fields.

        Assertions:
            - The "our_number" field matches the expected value.
            - The "digitable_line" field matches the expected digitable line format.
            - The "barcode" field matches the expected barcode value.
        """
        boleto_info = self.payment_transaction._prepare_transaction_boleto_info(
            SEND_CAPTURE_REQUEST_RESPONSE
        )

        self.assertEqual(boleto_info["our_number"], "123456789")
        self.assertEqual(
            boleto_info["digitable_line"],
            "12345.67890 12345.678901 12345.678901 1 23456789012345",
        )
        self.assertEqual(
            boleto_info["barcode"],
            "12345678901234567890123456789012345678901234",
        )

    def test_send_payment_request(self):
        """
        Test the `_send_payment_request` method of the payment transaction.

        This test verifies the following:
        1. The `_boleto_pinbank_make_request` method is called with the correct
           endpoint and payload.
        2. The payment transaction state is updated to "authorized".
        3. The response from `_send_payment_request` matches the mocked response.
        4. The payment transaction is updated with the correct boleto information,
           including `our_number`, `digitable_line`, `barcode`, and `boleto_pdf`.

        Mocked Data:
        - A mock response simulating the API response for generating a boleto.

        Assertions:
        - The mocked `_boleto_pinbank_make_request` method is called exactly once
          with the expected endpoint and payload.
        - The response returned by `_send_payment_request` matches the mocked response.
        - The payment transaction fields are updated with the expected boleto data.
        """
        mock_response = {
            "Data": {
                "NossoNumero": "123456789",
                "LinhaDigitavel": (
                    "12345.67890 12345.678901 12345.678901 1 23456789012345"
                ),
                "CodigoBarras": "12345678901234567890123456789012345678901234",
                "Base64": "bW9ja2VkX3BkZl9iYXNlNjQ=",
            },
        }

        payload = (
            self.payment_transaction._boleto_pinbank_prepare_order_request_payload()
        )

        with patch(
            "odoo.addons.l10n_br_payment_boleto_pinbank.models.payment_provider."
            "Paymentprovider._boleto_pinbank_make_request",
            return_value=mock_response,
        ) as mock_make_request:
            response = self.payment_transaction._send_payment_request()

            # Assert that the mocked method was called with the correct endpoint
            # and payload
            mock_make_request.assert_called_once_with(
                endpoint="/CashIn/GerarBoletoEncrypted",
                payload=payload,
            )

            # Assert that the response matches the mocked response
            self.assertEqual(response, mock_response)

            # Assert that the payment transaction state was updated to "pending"
            # (a newly created boleto has last_action=CREATED which maps to pending)
            self.assertEqual(self.payment_transaction.state, "pending")

            # Assert that the transaction was updated with the boleto info
            self.assertEqual(self.payment_transaction.our_number, "123456789")
            self.assertEqual(
                self.payment_transaction.digitable_line,
                "12345.67890 12345.678901 12345.678901 1 23456789012345",
            )
            self.assertEqual(
                self.payment_transaction.barcode,
                "12345678901234567890123456789012345678901234",
            )
            self.assertEqual(
                self.payment_transaction.boleto_pdf,
                b"bW9ja2VkX3BkZl9iYXNlNjQ=",
            )

    def test_send_capture_request(self):
        """
        Test the `_send_capture_request` method of the payment transaction.

        This test verifies the following:
        1. The `_boleto_pinbank_make_request` method is called with the correct endpoint
           and payload when `_send_capture_request` is executed.
        2. The state of the payment transaction is updated to "authorized" after the
           capture request is sent.
        3. The payment transaction is updated with the correct boleto information,
           including `our_number`, `digitable_line`, and `barcode`.

        Mocked Dependencies:
        - `odoo.addons.l10n_br_payment_boleto_pinbank.models.payment_provider.Paymentprovider
          ._boleto_pinbank_make_request`: Mocked to simulate the response of the
          external request.

        Assertions:
        - The mocked `_boleto_pinbank_make_request` method is called once with the
          expected endpoint and payload.
        - The `state` of the payment transaction is updated to "authorized".
        - The `our_number`, `digitable_line`, and `barcode` fields of the payment
          transaction are updated with the expected values.
        """
        self.payment_transaction.our_number = "123456789"

        with patch(
            "odoo.addons.l10n_br_payment_boleto_pinbank.models.payment_provider."
            "Paymentprovider._boleto_pinbank_make_request",
            return_value=SEND_CAPTURE_REQUEST_RESPONSE_REGISTRADO,
        ) as mock_make_request:
            self.payment_transaction._send_capture_request()

            # Assert that the mocked method was called with the correct endpoint
            # and payload
            mock_make_request.assert_called_once_with(
                "/CashIn/ConsultarBoletoEncrypted",
                payload=SEND_CAPTURE_REQUEST_PAYLOAD,
            )

            # Assert that the payment transaction state was updated to "authorized"
            self.assertEqual(self.payment_transaction.state, "authorized")

            # Assert that the transaction was updated with the boleto info
            self.assertEqual(self.payment_transaction.our_number, "123456789")
            self.assertEqual(
                self.payment_transaction.digitable_line,
                "12345.67890 12345.678901 12345.678901 1 23456789012345",
            )
            self.assertEqual(
                self.payment_transaction.barcode,
                "12345678901234567890123456789012345678901234",
            )
